### ISSUE TITLE
spring bug

### ISSUE THREAD

**Issue by Smi1eSEC** [kyo-w/router-router#3]
扫描致远oa 获取不到spirng instances
<img width="1352" alt="image" src="https://github.com/kyo-w/router-router/assets/39610144/9dc478f9-8b56-4fa4-85f3-896db96020e5">

<img width="1260" alt="image" src="https://github.com/kyo-w/router-router/assets/39610144/d3a5e1de-7c6e-4b57-976f-456e666dac8b">

**Comment by kyo-w** [comment]
是否可以方便提供一下你测试的致远oa版本

**Comment by Smi1eSEC** [comment]
a8+ v7.1sp1 方便留个微信吗

**Comment by kyo-w** [comment]
已发邮箱私信

**Comment by Smi1eSEC** [comment]
没看到哎




Smi1e
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kyo-w/router-router"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月27日(星期二) 晚上6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kyo-w/router-router] spring bug (Issue #3)





 
已发邮箱私信

**Comment by kyo-w** [comment]
wx: xiaosecurity

**Comment by kyo-w** [comment]
v4.2中做了一些修改,不再单独分析org.springframework.web.servlet.DispatcherServlet的存在,现在考虑继承org.springframework.web.servlet.DispatcherServlet做扩展的模式
